# Generated by Django 2.1.5 on 2020-01-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='チーム名')),
                ('serialcd', models.CharField(blank=True, max_length=255, verbose_name='シリアルコード')),
                ('team', models.IntegerField(blank=True, default=0, verbose_name='チーム')),
            ],
        ),
    ]
