# Generated by Django 2.1.5 on 2019-09-21 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ページ名')),
                ('serialcd', models.CharField(max_length=255, verbose_name='シリアルコード')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='メモ')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='rel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Members', to='cms.Page', verbose_name=''),
        ),
    ]
