# Generated by Django 2.1.5 on 2019-09-21 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190921_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Members', to='cms.Page', verbose_name=''),
        ),
    ]
