# Generated by Django 2.1.5 on 2019-09-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190921_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='rel',
        ),
        migrations.AddField(
            model_name='member',
            name='serialcd',
            field=models.CharField(blank=True, max_length=255, verbose_name='シリアルコード'),
        ),
    ]
